### ISSUE TITLE
Attribution property

### ISSUE THREAD

**Issue by tmcw** [yohanboniface/geocodejson-spec#14]
One of the [optional properties of carmen-geojson](https://github.com/mapbox/carmen/blob/master/carmen-geojson.md) which is probably also needed for several other geocoders, both commercial and open, is `attribution`, which should note requires for credit and usage of geocoding results.

**Comment by yohanboniface** [comment]
Humm, don't we have it [here](https://github.com/geocoders/geocodejson-spec/blob/master/draft/README.md#main-object) ? Or are you talking about something else?

**Comment by tmcw** [comment]
:| whoah missed that :)

**Comment by yohanboniface** [comment]
That's a proof that even the best of us fails sometimes ;)

**Comment by tmcw** [comment]
<strike>sometimes</strike> very often

**Comment by yohanboniface** [comment]
"failing as the best way to grow up"? :)
