### ISSUE TITLE
What does "county" mean?

### ISSUE THREAD

**Issue by Flaburgan** [yohanboniface/geocodejson-spec#20]
In the spec:
```
      // OPTIONAL. County of the place.
      "county": null,

      // OPTIONAL. State of the place.
      "state": null,

      // OPTIONAL. Country of the place.
      "country": "France",
```

Is `county` a typo for `country`? But then there's `country` just after... ??

**Comment by yohanboniface** [comment]
https://en.wikipedia.org/wiki/County

It's an administrative level we don't have in France :)

**Comment by Flaburgan** [comment]
Alright, thank you. Is it worth adding this link in the spec?
