### ISSUE TITLE
Interest in Starting This Up Again?

### ISSUE THREAD

**Issue by DanielJDufour** [yohanboniface/geocodejson-spec#21]
:wave: Hello.  I'd like to contribute to creating a standard for geocoding responses.  Some of my tasks will be to put the schema in a JSON-Schema format (https://json-schema.org/) and also create a web app that can validate results checking conformance with the schema as well as suggesting improvements and plugins to the existing schema.

What is the best way for me to help?  Should I contribute Pull Requests to this repository or should I create my own repo?  Thank you and have a great day :-)

**Comment by yohanboniface** [comment]
Hey, sorry for my very late answer, I'm mainly offline these days (and will be until end of month): you are welcome to contribute PR to this repository :)
It's not very active as you can see, but that may be a way to wake it up :)

**Comment by DanielJDufour** [comment]
Awesome.  I'll be contributing some PR's soon!
