### ISSUE TITLE
Introduce a namespace for properties specific to geocodejson-spec

### ISSUE THREAD

**Issue by sgillies** [yohanboniface/geocodejson-spec#3]
Introducing properties like "name", "label", "accuracy" into feature properties simply won't work; collisions with other applications are certain. To avoid collisions, I recommend creating a namespace for properties specific to this application – `geocoding`, maybe – and define properties like `feature['properties']['geocoding']['name']`. A `collection['version']` property won't work for the same reason, and so I also recommend a `geocoding` namespace for the feature collection object.

This approach is being used at https://github.com/mapbox/geojson-coordinate-properties.

**Comment by yohanboniface** [comment]
Good points! I'll consider that :)
